defaults:
  - experiment
  - model: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

checkpoint: ???
job_type: correct

hydra:
  searchpath:
    - file:///etc/m3l
    - file://${oc.env:HOME}/.config/m3l