# @package _global_
defaults:
  - /data: varied_patch
  - /net: qgac_crab

trainer:
  max_epochs: 200

net:
  learning_config:
    optimizer:
      lr: 1e-4
    scheduler:
      eta_min: 1e-6

name: qgac_crab
  