# @package _global_
defaults:
  - /data: varied_patch
  - /net: qgac_crab
  - optional /overrides: qgac_crab

trainer:
  max_epochs: 200
  replace_sampler_ddp: no

net:
  optimizer:
    lr: 1e-4
  scheduler:
    eta_min: 1e-6

name: qgac_crab
  