[tool.poetry]
name = "mme"
version = "0.0.0" 
description = "Multimedia Enhancement and Correction "
authors = [
    "Max Ehrlich"
]

license = "MIT"
readme = "README.md"

homepage = ""
repository = ""
documentation = ""


classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Development Status :: 3 - Alpha"
]

[tool.poetry.dependencies]
python = ">= 3.6.1, < 3.9"
pillow = "^8.0.1"
torchvision = "^0.8.1"
pytorch-lightning = "^1.1.1"
hydra-core = { git = "https://github.com/facebookresearch/hydra.git" }
submitit = { git = "https://github.com/facebookincubator/submitit.git" }
yaspin = "^1.2.0"
torchjpeg = "^0.9.11"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
pylint = "^2.6.0"

[build-system]

requires = [
    "poetry>=1.0.10",
]
build-backend = "poetry.masonry.api"