defaults:
  - experiment
  - data: varied_patch
  - model: qgac_crab

trainer:
  max_epochs: 200

model:
  learning_config:
    optimizer:
      lr: 1e-3
    scheduler:
      eta_min: 1e-6

name: qgac_crab
  