defaults:
  - experiment
  - model: ???
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

checkpoint: ???
job_type: test

hydra:
  searchpath:
    - file:///etc/mm
    - file://${oc.env:HOME}/.config/mm