# @package _global_
defaults:
  - /data: varied_patch
  - /net: qgac_crab
  - /callbacks:
    - best    
  - optional /overrides: qgac_crab
  - override /serializer: image_serializer

trainer:
  max_epochs: 200
  replace_sampler_ddp: no

net:
  optimizer:
    lr: 1e-4
  scheduler:
    eta_min: 1e-6

callbacks:
  best:
    monitor: val/psnr
    filename: best-epoch{epoch:03d}-psnr{val/psnr:.2f}

name: qgac_crab
  