# @package _global_
defaults:
  - /data: varied_patch
  - /net: qgac_crab
  - optional /overrides: qgac_crab
  - override /serializer: image_serializer

trainer:
  max_epochs: 200
  replace_sampler_ddp: no

net:
  optimizer:
    lr: 1e-4
  scheduler:
    eta_min: 1e-6

callbacks:
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/psnr
    mode: max
    filename: best-epoch{epoch:03d}-psnr{val/psnr:.2f}
    auto_insert_metric_name: no

name: qgac_crab
  