_target_: pytorch_lightning.Trainer
resume_from_checkpoint: ${checkpoint}
plugins:
  - _target_: pytorch_lightning.plugins.DDPPlugin
    find_unused_parameters: no
callbacks:
  - _target_: m3l.run.M3LProgress